title: GBC Tech Docs
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

plugins:
- jekyll-remote-theme

exclude: ["README.md"]

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/zachary-gbc/tech-help-docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
